spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/books
    username: postgres
    password: postgres
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql

    properties:
      hibernate:
        format_sql: true
        debug: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      type:
        descriptor:
          sql: trace
